
network: "phykan"

layers: 
- 784
- 200
- 200
- 10  

filters_per_unit: 1
thresholding: False 
lr_decay: 1
sigmoid_s: 0.5

lambda: 1

noisy: False

batch_size: 250
val_batch_size: 1000

epochs: 10
learning_rate: 0.01
